export const vehicledata = [{id:1,car:"Supra",make:"Toyota",year:"2020",dailyRate:250,imgs:["https://www.motorbiscuit.com/wp-content/uploads/2020/05/2021-Toyota-Supra.jpg"],
specs:{engineType:"Turbo-Charged Inline 6", drivetrain:"Rear Wheel Drive", transmission:"8-Speed Automatic"},
description:"Supra Stuff"},
{id:2,car:"TT",make:"Audi",year:"2016",dailyRate:250,imgs:["https://s1.cdn.autoevolution.com/images/models/AUDI_TTS-Coupe-Competition-Plus-2020_main.jpg"],
specs:{engineType:"Turbo-Charged Inline 6", drivetrain:"All Wheel Drive", transmission:"6-Speed Automatic"},
description:"TT Stuff"},
{id:3,car:"Civic Type R",make:"Honda",year:"2019",dailyRate:250,imgs:["https://lh3.googleusercontent.com/proxy/9oSD-6R8AGe_cW9kSEqOD6W1poamy8Mj1uNFEdvyrVjXPNVXk6fsS0rcTw9jWCu1SbvXJQWbWv4X-coA-3Ft8EcxRdG68SZoGdgEJbyvZcePb9Nv4lB51YTjTEicq-W8L6-BJ3ullb4Fnvl1_VoCM_R9yfAa546D"],
specs:{engineType:"Turbo-Charged Inline 4", drivetrain:"Front Wheel Drive", transmission:"Manual"},
description:"Type R Stuff"},
{id:4,car:"WRX STi",make:"Subaru",year:"2015",dailyRate:250,imgs:["https://static01.nyt.com/images/2014/04/02/multimedia/driven-subaru-wrxsti/driven-subaru-wrxsti-superJumbo.jpg"],
specs:{engineType:"Turbo-Charged Boxer 4", drivetrain:"All Wheel Drive", transmission:"Manual"},
description:"STi Stuff"}]